---
name: Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: read-all

env:
  BUILD_TAG: wkobiela/ammo_front:PR-${{ github.event.number }}

jobs:
  build:
    name: Build image
    runs-on: self-hosted

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set BUILD_TAG
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "BUILD_TAG=wkobiela/ammo_front:PR-${{ github.event.number }}" >> $GITHUB_ENV
        else
          DATE=$(date +"%d.%m.%Y")
          echo "BUILD_TAG=wkobiela/ammo_front:$DATE" >> $GITHUB_ENV
        fi
        echo "LATEST_TAG=wkobiela/ammo_front:latest" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup mariadb container
      run: |
        docker run --name mariadb --rm -d -p 3306:3306 \
        -e MYSQL_ROOT_PASSWORD=root \
        --health-cmd="healthcheck.sh --connect --innodb_initialized" \
        --health-interval=10s \
        --health-timeout=5s --health-retries=3 \
        mariadb:latest

    - name: Wait until mariadb container is healthy
      uses: raschmitt/wait-for-healthy-container/@master
      with:
        container-name: mariadb
        timeout: 120

    - name: Initialize MariaDB with SQL script
      run: |
        echo "Initialize database -> pushing initialize_db.sql to MariaDB instance."
        docker exec -i mariadb mariadb -uroot -proot < .github/configs/initialize_db.sql
        echo "Show databases ->"
        docker exec mariadb mariadb --table -e "SHOW DATABASES;" -uroot -proot | column -t -s $'\t'
        echo "Describe example_table ->"
        docker exec mariadb mariadb --table -e "USE example_database; DESCRIBE example_table;" -uroot -proot | column -t -s $'\t'
        echo "Show content of example_table ->"
        docker exec mariadb mariadb -e "USE example_database; SELECT * FROM example_table;" -uroot -proot | column -t -s $'\t'
        echo "Get mariadb hostname IP address ->"
        DB_HOST=$(docker exec mariadb hostname -I)

    - name: Build and export to Docker
      uses: docker/build-push-action@v6
      with:
        context: ${{ github.workspace }}
        load: true
        tags: ${{ env.BUILD_TAG }}

    - name: Run Docker container
      run: |
        docker run --name test --rm -d -p 3000:3000 \
        -e DB_HOST=$DB_HOST \
        -e DB_USER=root \
        -e DB_PASSWORD=root \
        -e DB_DATABASE=example_database \
        -e DB_TABLE=example_table \
        -e DB_PORT=3306 \
        ${{ env.BUILD_TAG }}

    - name: Wait until the container is healthy
      uses: raschmitt/wait-for-healthy-container/@master
      with:
        container-name: test
        timeout: 120

    - name: Verify if working
      run: |
        response=$(curl -s http://localhost:3000/status || exit 1)
        echo "Server response: $response"

        main_page_status=$(echo "$response" | jq -r '.["Main page status"]')
        db_status=$(echo "$response" | jq -r '.["Database connection"]')

        if [[ "$main_page_status" != "ACTIVE" || "$db_status" != "ACTIVE" ]]; then
          echo "Error: One or both services are not ACTIVE"
          exit 1
        fi
        echo "Test PASSED"

#    - name: Login to Docker Hub
#      uses: docker/login-action@v3
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#    - name: Push to Docker Hub
#      uses: docker/build-push-action@v6
#      with:
#        push: true
#        tags: ${{ env.BUILD_TAG }}
#
#    - name: Remove container and local image
#      if: always()
#      run: |
#        docker rm --force test
#        docker rm --force mariadb
#        docker rmi --force ${{ env.BUILD_TAG }}